// Types para el context de products 

export const OBTENER_PRODUCTS = 'OBTENER_PRODUCTS';
export const OBTENER_PRODUCTS_SUCCESS = 'OBTENER_PRODUCTS_SUCCESS';
export const OBTENER_PRODUCTS_ERROR = 'OBTENER_PRODUCTS_ERROR';
export const OBTENER_PRODUCT_SUCCESS = 'OBTENER_PRODUCT_SUCCESS';
export const OBTENER_PRODUCT_ERROR = 'OBTENER_PRODUCT_ERROR';